In [10]:
import numpy as np

input = np.array([[1,2,3],[4,5,6],[7,8,9]])
filter = np.array([[1,2,1],[0,0,0],[-1,-2,-1]])

input1 = input.reshape(-1,1)

x = np.zeros((filter.shape[0],filter.shape[1],3))


for i in range(x.shape[0]):
  for j in range(x.shape[2]):
    filter1 = filter[filter.shape[0]-i-1]
    x[i,:,j] = np.roll(filter1,j).transpose()
   

result = np.zeros((filter.shape[0]*filter.shape[1],input1.shape[0]))
for i in range(result.shape[1]//x.shape[2]):
  result[:,x.shape[2]*i:x.shape[2]*(i+1)] = np.reshape(np.roll(x,i,axis=0),(-1,x.shape[2]))
print(result)

print((np.dot(result,input1)).reshape(filter.shape[0],filter.shape[1]))

[[-1. -1. -2.  1.  1.  2.  0.  0.  0.]
 [-2. -1. -1.  2.  1.  1.  0.  0.  0.]
 [-1. -2. -1.  1.  2.  1.  0.  0.  0.]
 [ 0.  0.  0. -1. -1. -2.  1.  1.  2.]
 [ 0.  0.  0. -2. -1. -1.  2.  1.  1.]
 [ 0.  0.  0. -1. -2. -1.  1.  2.  1.]
 [ 1.  1.  2.  0.  0.  0. -1. -1. -2.]
 [ 2.  1.  1.  0.  0.  0. -2. -1. -1.]
 [ 1.  2.  1.  0.  0.  0. -1. -2. -1.]]
[[ 12.  12.  12.]
 [ 12.  12.  12.]
 [-24. -24. -24.]]
